spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/people-management
    username: postgres
    password: sigfpto
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate.format_sql: true
    open-in-view: false
  mvc:
    path match:
      matching-strategy: ant-path-matcher
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
email-microservice-url: https://ms-microservice.herokuapp.com








